### ISSUE TITLE
cannot convert mathematical formula ?

### ISSUE THREAD

**Issue by zjd1988** [spawnia/md-to-pdf#12]
excellent work!!!! 
I have try 
```
$$
kernel = \frac{1}{9}\left[
 \begin{matrix}
   1 & 1 & 1 \newline
   1 & 1 & 1 \newline
   1 & 1 & 1
  \end{matrix}
  \right]
$$
```

but not work.

**Comment by spawnia** [comment]
Works for me when using the conversion engine `pdflatex`.

![image](https://github.com/spawnia/md-to-pdf/assets/12158000/bc90d54f-98e8-4790-9814-510a22afa24d)

![image](https://github.com/spawnia/md-to-pdf/assets/12158000/7d5b6eb2-27b6-494c-84b7-d8cfbc6b99f0)

**Comment by zjd1988** [comment]
@spawnia newline not works
```
\newline
```
