### ISSUE TITLE
Error with Nested Lists

### ISSUE THREAD

**Issue by zaakirio** [spawnia/md-to-pdf#13]
Lists written in the form:
1. A
2. B
3. C
   3.1 D
   3.2 E
   3.3 F
   3.4 G
4. H

Are rendered on a single line and not treated as nested lists

**Comment by spawnia** [comment]
This project is a very thin wrapper around Pandoc, which handles the actual conversion from Markdown (+ CSS) to PDF. The values given through the UI/API are passed to Pandoc untouched and the converted result is returned. See https://github.com/spawnia/md-to-pdf/blob/master/src/main.rs.
