### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by arjunpredev** [spawnia/md-to-pdf#17]
Is it possible to increase the size of the Markdown Payload?

**Comment by spawnia** [comment]
This should be possible by setting an environment variable prefixed with `ROCKET_` in the container, see https://rocket.rs/guide/v0.5/configuration/#environment-variables. The current limit is set to `128KiB`, see https://github.com/spawnia/md-to-pdf/blob/d9b97e84d1a5eb15e9644cbec204fc45c7876816/Rocket.toml#L6.

Can you try something like the following and report back with the results?

```env
ROCKET_LIMITS={form="256KiB"}
```

**Comment by arjunpredev** [comment]
Is there an absolute max size? We have some markdowns that exceed 10MB?

**Comment by spawnia** [comment]
https://rocket.rs/guide/v0.5/configuration/#limits indicates no such upper bound, please try it out and report your findings.
