### ISSUE TITLE
Issue deploying to fly.io

### ISSUE THREAD

**Issue by mlava** [spawnia/md-to-pdf#3]
Hi there. I got the Docker container working locally and it outputs beautifully.
I am having trouble deploying it to fly.io. I think the issue is in my Dockerfile.

```
FROM spawnia/md-to-pdf

CMD ["md-to-pdf", "-", "-o", "output.pdf"]
```

I'm sure it's wrong and will appreciate any advice. Thanks in advance!

**Comment by spawnia** [comment]
The `md-to-pdf` executable accepts no arguments. The pre-built container should work as is, I am deploying it to fly.io as well.

**Comment by mlava** [comment]
Sorry, I am not sure I understand. Does that mean my Dockerfile CMD line should just read:

CMD ["md-to-pdf"]

**Comment by spawnia** [comment]
You do not need the line at all, it is already baked into the image as `CMD ["md-to-pdf"]`.

**Comment by mlava** [comment]
I am sorry to be such a noob. Thank you. I am having trouble deploying to fly.io and thought I needed a Dockerfile to deploy. I presume there's a way to deploy without a Dockerfile?

**Comment by spawnia** [comment]
Possible. I won't do tech support for fly.io here though 😉
