### ISSUE TITLE
Web service not working

### ISSUE THREAD

**Issue by norama** [spawnia/md-to-pdf#5]
There is some security issue here, I could not use this service:

```
curl --data-urlencode "markdown='# Heading 1'" --output md-to-pdf.pdf https://md-to-pdf.fly.dev
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) 
```

Also tried from PostMan and React web app, but got 422 Unprocessable Entity error.
How to fix this?

**Comment by spawnia** [comment]
The above command works for me. Perhaps there is an issue with your network or the version of curl you are using? Try running the image locally as described in https://github.com/spawnia/md-to-pdf#deploy and check the container logs.

**Comment by norama** [comment]
Thank you. Actually I had to apply the
```
-k or --insecure
```
curl flag, and put quotes in a different way:
```
curl -k https://md-to-pdf.fly.dev --data-urlencode markdown="# Heading 1" --output md-to-pdf.pdf
```
and this is working.

However, I am still having trouble to call this service from browser / javascript `fetch()`,
there was some CORS problem, so I try to set 'no-cors' but the returned BLOB is empty and `ok` flag is `false`:

```
 const data = new URLSearchParams()
  data.append('markdown', markdown)
  if (css) {
    data.append('css', css)
  }

  const response = await fetch(PDF_EXPORT_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    mode: 'no-cors',
    body: data,
  })

  const blob = await response.blob()
  console.log('blob', blob)
```

This blob is empty, what am I doing wrong here?
Possibly I cannot call this service from localhost?

**Comment by norama** [comment]
I deployed it to github pages:
https://norama.github.io/mdx-editor/

but it fails with the same result, empty BLOB.

**Comment by spawnia** [comment]
I enabled CORS with https://github.com/spawnia/md-to-pdf/releases/tag/v1.3.0, please try again.

**Comment by norama** [comment]
Thanks a lot, that was the problem. 
Everything is working fine now, from localhost as well as from deployed version.

**Comment by norama** [comment]
Unfortunately the same CORS problem reappeared:

```
Access to fetch at 'https://md-to-pdf.fly.dev/' from origin 'https://norama.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Have you changed here something?

**Comment by spawnia** [comment]
The application as a whole is down. Thus, Fly responded with a 503 that does not include CORS headers. I modified this with https://github.com/spawnia/md-to-pdf/commit/cfa24edcdea3110a981998fd9efb718752af1843 and am investigating why the application is down.

**Comment by spawnia** [comment]
It is working again.
